spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: P@$$w0rd
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
name: test-YAML
environment: test

server:
  port: 9000

banner:
  location: banner